### ISSUE TITLE
train failed

### ISSUE THREAD

**Issue by Ciao-Z** [caiqi/sample-weighting-network#6]
Here is my environment:
python3.6.5, pytorch1.2.0, torchvision 0.4.0, cuda9.2, gcc 5.4.0, RTX 2080 ti.
when i run the "bash scripts/Mask_R50.sh", the error occurred:
(1) RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation:  [torch.cuda.FloatTensor [45, 256, 14, 14]], which is output 0 of IndexPutBackward, is at version 4; expected version 3 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).
(2) Traceback (most recent call last):
  File "/home/super2/anaconda3/envs/pytorch1.2+9.2/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/super2/anaconda3/envs/pytorch1.2+9.2/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/super2/anaconda3/envs/pytorch1.2+9.2/lib/python3.6/site-packages/torch/distributed/launch.py", line 246, in <module>
    main()
  File "/home/super2/anaconda3/envs/pytorch1.2+9.2/lib/python3.6/site-packages/torch/distributed/launch.py", line 242, in main
    cmd=cmd)
  subprocess.CalledProcessError: Command '['/home/super2/anaconda3/envs/pytorch1.2+9.2/bin/python', '-u', './tools/train.py', '--local_rank=1', 'configs/Mask_R50.py', '--launcher', 'pytorch', '--validate']' returned non-zero exit status 1.
(3) Traceback (most recent call last):                                                                                                                 
  File "./tools/test.py", line 213, in <module>
    main()
  File "./tools/test.py", line 201, in main
    coco_eval(result_files, eval_types, dataset.coco, in_detail=args.in_detail)
  File "/home/super2/zhaochao/detection/sample-weighting-network/mmdet/core/evaluation/coco_utils.py", line 110, in coco_eval
    coco_dets = coco.loadRes(result_file)
  File "/home/super2/anaconda3/envs/pytorch1.2+9.2/lib/python3.6/site-packages/pycocotools-2.0-py3.6-linux-x86_64.egg/pycocotools/coco.py", line 326, in loadRes
    if 'caption' in anns[0]:
IndexError: list index out of range.
(4) Traceback (most recent call last):
  File "/home/super2/anaconda3/envs/pytorch1.2+9.2/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/super2/anaconda3/envs/pytorch1.2+9.2/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/super2/anaconda3/envs/pytorch1.2+9.2/lib/python3.6/site-packages/torch/distributed/launch.py", line 246, in <module>
    main()
  File "/home/super2/anaconda3/envs/pytorch1.2+9.2/lib/python3.6/site-packages/torch/distributed/launch.py", line 242, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/super2/anaconda3/envs/pytorch1.2+9.2/bin/python', '-u', './tools/test.py', '--local_rank=1', 'configs/Mask_R50.py', 'work_dirs/Mask_R50/latest.pth', '--launcher', 'pytorch', '--out', 'work_dirs/Mask_R50/results.pkl', '--eval', 'bbox', '--in_detail', '1']' returned non-zero exit status 1.

What do i need to do to successfully to train the model?
Look forward to answers.
Thanks

**Comment by caiqi** [comment]
I have run the code locally and there is no error. For error (1), it seems due to in-place operation. Could you run "torch.autograd.set_detect_anomaly(True)" as suggested in error (1).  For error (3), it seems due to the annotation format. For error (2) and error (4), I can figure out why it fails from the given information. Maybe you could provide more information so that I can help. Thanks.
